# Generated by Django 2.2 on 2020-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('firstname', models.CharField(max_length=64)),
                ('lasttname', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('dateofbirth', models.DateField(max_length=8)),
                ('company', models.CharField(max_length=256)),
            ],
        ),
    ]
