# Generated by Django 2.2 on 2020-09-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
